1. 5×5 matrix with values 1 to 25

In [ ]:
import numpy as np
matrix = np.arange(1, 26).reshape(5, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


2. 4×4 identity matrix

In [ ]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


3. 1D array from 100 to 200 with step 10

In [ ]:
arr = np.arange(100, 201, 10)
print(arr)

[100 110 120 130 140 150 160 170 180 190 200]


4. Random 3×3 matrix and its determinant

In [ ]:
mat = np.random.rand(3, 3)
det = np.linalg.det(mat)
print(mat)
print("Determinant:", det)

[[0.83182124 0.28150054 0.24175991]
 [0.82600831 0.92283963 0.64705924]
 [0.69569147 0.03346176 0.0946425 ]]
Determinant: 0.010822285436998239


5. 10 random integers between 1 and 100

In [ ]:
rand_ints = np.random.randint(1, 101, size=10)
print(rand_ints)

[53 45 35 46 68 21 38 64 54 38]


6. Reshape 1D array of size 12 into 3×4

In [ ]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


7. Matrix multiplication of two 3×3 matrices

In [ ]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
result = np.dot(A, B)
print(result)

[[0.94945259 0.68061711 0.56125179]
 [1.19458895 0.98922026 0.84110139]
 [0.94256246 0.71200821 0.61347563]]


8. Eigenvalues and eigenvectors of a 2×2 matrix

In [ ]:
matrix = np.array([[4, -2], [1, 1]])
eigvals, eigvecs = np.linalg.eig(matrix)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


9. Extract diagonal from 5×5 random matrix

In [ ]:
mat = np.random.rand(5, 5)
diagonal = np.diag(mat)
print(diagonal)

[0.58924668 0.92392298 0.17130428 0.45524028 0.66347901]


10. Normalize a 1D array between 0 and 1

In [ ]:
arr = np.random.rand(10)
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

[1.         0.70404008 0.76830576 0.95090948 0.         0.79175626
 0.23552944 0.87884732 0.60779141 0.62225108]


11. Sort array by rows and columns

In [ ]:
arr = np.random.randint(1, 100, (4, 4))
row_sorted = np.sort(arr, axis=1)
col_sorted = np.sort(arr, axis=0)
print("Row-wise sorted:\n", row_sorted)
print("Column-wise sorted:\n", col_sorted)

Row-wise sorted:
 [[36 49 54 90]
 [65 67 79 95]
 [10 28 88 99]
 [ 1 31 93 94]]
Column-wise sorted:
 [[31  1 10 28]
 [67 54 36 49]
 [90 65 94 79]
 [99 88 95 93]]


12. Indices of max and min in array

In [ ]:
arr = np.random.rand(10)
max_index = np.argmax(arr)
min_index = np.argmin(arr)
print("Max index:", max_index)
print("Min index:", min_index)

Max index: 4
Min index: 1


13. Flatten 2D array using ravel() and flatten()

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr.ravel())
print(arr.flatten())

[1 2 3 4]
[1 2 3 4]


14. Inverse of 3×3 matrix

In [ ]:
mat = np.random.rand(3, 3)
inv = np.linalg.inv(mat)
print(inv)

[[ 0.35912537 -2.98691103  0.92070073]
 [-0.82095738  2.69440126  0.59695959]
 [ 1.83137716  2.30928936 -1.65651307]]


15. Random permutation of numbers 1 to 10

In [ ]:
perm = np.random.permutation(np.arange(1, 11))
print(perm)

[ 9  1  3  2  4  7  8  6 10  5]


16. Replace even numbers with -1

In [ ]:
arr = np.arange(21)
arr[arr % 2 == 0] = -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


17. Dot product of two arrays

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)
print(dot)

32


18. Trace of 5×5 random matrix

In [ ]:
mat = np.random.rand(5, 5)
trace = np.trace(mat)
print(trace)

2.8335859117148483


19. Split array into 3 equal parts

In [ ]:
arr = np.arange(15)
splits = np.array_split(arr, 3)
for part in splits:
    print(part)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


20. 3D array mean across axis=0

In [ ]:
arr = np.random.rand(3, 3, 3)
mean = arr.mean(axis=0)
print(mean)

[[0.36692231 0.65981677 0.47812653]
 [0.42544473 0.42185896 0.40235592]
 [0.290372   0.59342857 0.66088084]]


21. Cumulative sum of array

In [ ]:
arr = np.array([1, 2, 3, 4])
cumsum = np.cumsum(arr)
print(cumsum)

[ 1  3  6 10]


22. Extract upper triangular of 4×4 matrix

In [ ]:
mat = np.random.randint(1, 10, (4, 4))
upper_tri = np.triu(mat)
print(upper_tri)

[[1 1 9 6]
 [0 8 4 6]
 [0 0 6 8]
 [0 0 0 7]]


23. 6×6 checkerboard matrix

In [ ]:
checkerboard = np.indices((6, 6)).sum(axis=0) % 2
print(checkerboard)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


24. Element-wise square root

In [ ]:
mat = np.random.rand(3, 3)
sqrt_mat = np.sqrt(mat)
print(sqrt_mat)

[[0.48424534 0.70864931 0.84831093]
 [0.86826189 0.5789574  0.79600387]
 [0.69041932 0.46839178 0.93244164]]


25. Reverse array without slicing

In [ ]:
arr = np.arange(20)
reversed_arr = np.flip(arr)
print(reversed_arr)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


26. Merge arrays vertically & horizontally

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
vertical = np.vstack((a, b))
horizontal = np.hstack((a, b))
print("Vertical:\n", vertical)
print("Horizontal:\n", horizontal)

Vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


27. Row-wise & column-wise sum

In [ ]:
arr = np.random.randint(1, 10, (3, 3))
row_sum = arr.sum(axis=1)
col_sum = arr.sum(axis=0)
print("Row sum:", row_sum)
print("Column sum:", col_sum)

Row sum: [16 17 17]
Column sum: [13 19 18]


28. Replace NaN with column mean

In [ ]:
arr = np.array([[1, 2, np.nan], [4, np.nan, 6]])
col_means = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_means, inds[1])
print(arr)

[[1. 2. 6.]
 [4. 2. 6.]]


29. Cosine similarity between arrays

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cos_sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print("Cosine Similarity:", cos_sim)

Cosine Similarity: 0.9746318461970762


30. Rotate 4×4 array by 90 degrees

In [ ]:
arr = np.arange(16).reshape(4, 4)
rotated = np.rot90(arr)
print(rotated)

[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]


31. Structured array (name, age, marks)

In [ ]:
data = np.array([('Alice', 25, 85.0), ('Bob', 23, 90.0)],
            dtype=[('name', 'U10'), ('age', 'i4'), ('marks', 'f4')])
print(data)

[('Alice', 25, 85.) ('Bob', 23, 90.)]


32. Rank of 3×3 matrix

In [ ]:
mat = np.random.rand(3, 3)
rank = np.linalg.matrix_rank(mat)
print("Rank:", rank)

Rank: 3


33. Normalize rows to unit length

In [ ]:
mat = np.random.rand(5, 5)
norms = np.linalg.norm(mat, axis=1, keepdims=True)
normalized = mat / norms
print(normalized)

[[0.4130663  0.60560047 0.50020714 0.33283637 0.31880571]
 [0.16986676 0.39592109 0.82389739 0.34456958 0.12983327]
 [0.47875861 0.22771091 0.4608365  0.26285364 0.6614194 ]
 [0.17798592 0.06515701 0.42027544 0.69406815 0.55291367]
 [0.07056404 0.62028173 0.65446136 0.41702955 0.08965472]]


34. Element-wise array equality

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])
equal = np.array_equal(a, b)
print(equal)

False


35. Histogram of 1000 numbers

In [ ]:
data = np.random.randn(1000)
hist, bins = np.histogram(data, bins=10)
print("Histogram:", hist)
print("Bins:", bins)


Histogram: [  1  12  28 110 227 278 197 103  33  11]
Bins: [-3.88683564 -3.1798526  -2.47286956 -1.76588652 -1.05890348 -0.35192044
  0.3550626   1.06204564  1.76902868  2.47601172  3.18299476]


36. Apply broadcasting

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
to_add = np.array([10, 20, 30])
result = arr + to_add
print(result)

[[11 22 33]
 [14 25 36]]


37. Unique values and counts

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 4])
vals, counts = np.unique(arr, return_counts=True)
print("Values:", vals)
print("Counts:", counts)

Values: [1 2 3 4]
Counts: [1 2 1 3]


38. Pearson correlation coefficient

In [ ]:
a = np.random.rand(100)
b = np.random.rand(100)
corr = np.corrcoef(a, b)[0, 1]
print("Pearson Correlation:", corr)

Pearson Correlation: 0.11008682681227272


39. Numerical gradient of a 1D array

In [ ]:
import numpy as np
arr = np.array([1, 2, 4, 7, 11])
gradient = np.gradient(arr)
print("Gradient:", gradient)

Gradient: [1.  1.5 2.5 3.5 4. ]


40. Singular Value Decomposition (SVD) of a 3×3 matrix

In [ ]:
import numpy as np
matrix = np.random.rand(3, 3)
U, S, Vt = np.linalg.svd(matrix)
print("Original matrix:\n", matrix)
print("U:\n", U)
print("Singular values:", S)
print("Vt:\n", Vt)

Original matrix:
 [[0.34621235 0.22573004 0.66456895]
 [0.2652687  0.22571921 0.68269563]
 [0.93060967 0.71969917 0.72356592]]
U:
 [[-0.44037953 -0.49452553 -0.74933995]
 [-0.41975804 -0.62438307  0.65874803]
 [-0.7936429   0.60464062  0.06738445]]
Singular values: [1.70910534 0.43022929 0.03562967]
Vt:
 [[-0.58649706 -0.44780065 -0.67490427]
 [ 0.52493934  0.42441284 -0.73777533]
 [-0.61681431  0.78698686  0.01384871]]
